package com.sida.dcloud.event.po.training;

import com.sida.dcloud.event.po.EventType;

public enum TrainingEventType implements EventType {
    TRAINING_EVENT_ICON_GROUP_INSERT,
    TRAINING_EVENT_ICON_GROUP_UPDATE,
    TRAINING_EVENT_ICON_GROUP_REMOVE,
    TRAINING_EVENT_ICON_GROUP_INCREASE_TOTAL,

    TRAINING_EVENT_ICON_INFO_INSERT,
    TRAINING_EVENT_ICON_INFO_UPDATE,
    TRAINING_EVENT_ICON_INFO_REMOVE,

    TRAINING_EVENT_AUDIO_SIMULATOR_INSERT,
    TRAINING_EVENT_AUDIO_SIMULATOR_UPDATE,
    TRAINING_EVENT_AUDIO_SIMULATOR_REMOVE,

    TRAINING_EVENT_LIGHTING_SIMULATOR_INSERT,
    TRAINING_EVENT_LIGHTING_SIMULATOR_UPDATE,
    TRAINING_EVENT_LIGHTING_SIMULATOR_REMOVE,

    TRAINING_EVENT_EXERCISE_INSERT,
    TRAINING_EVENT_EXERCISE_UPDATE,
    TRAINING_EVENT_EXERCISE_REMOVE,

    TRAINING_EVENT_SPECIAL_GROUP_INSERT,
    TRAINING_EVENT_SPECIAL_GROUP_UPDATE,
    TRAINING_EVENT_SPECIAL_GROUP_REMOVE,
    TRAINING_EVENT_SPECIAL_GROUP_INCREASE_TOTAL,

    TRAINING_EVENT_CHAPTER_SECTION_INSERT,
    TRAINING_EVENT_CHAPTER_SECTION_UPDATE,
    TRAINING_EVENT_CHAPTER_SECTION_REMOVE,
    TRAINING_EVENT_CHAPTER_SECTION_INCREASE_TOTAL,

    TRAINING_EVENT_FAVORITE_NOTE_INSERT,
    TRAINING_EVENT_FAVORITE_NOTE_UPDATE,
    TRAINING_EVENT_FAVORITE_NOTE_REMOVE,

    TRAINING_EVENT_EXAM_TRACK_ANSWER,
    TRAINING_EVENT_EXAM_TRACK_START,
    TRAINING_EVENT_EXAM_TRACK_END,
    TRAINING_EVENT_EXAM_TRACK_SHUFFLE,
    TRAINING_EVENT_EXAM_TRACK_REMOVE,

    TRAINING_EVENT_EXAM_RULE_MIX_UPDATE,

    TRAINING_EVENT_ERROR_NOTE_INSERT,
    TRAINING_EVENT_ERROR_NOTE_CORRECT,

    TRAINING_EVENT_TRAINING_USER_SETTING_SAVE,
}
