package com.sida.dcloud.event.po.activity;

import com.sida.dcloud.event.po.EventType;

public enum ActivityEventType implements EventType {
    ACTIVITY_EVENT_ACTIVITY_INFO_INSERT,
    ACTIVITY_EVENT_ACTIVITY_INFO_UPDATE,
    ACTIVITY_EVENT_ACTIVITY_INFO_REMOVE,

    ACTIVITY_EVENT_ACTIVITY_SIGNUP_NOTE_SETTING_INSERT,
    ACTIVITY_EVENT_ACTIVITY_SIGNUP_NOTE_SETTING_UPDATE,
    ACTIVITY_EVENT_ACTIVITY_SIGNUP_NOTE_SETTING_REMOVE,
}
