spring:
  application:
    name: @operation-module@
  rabbitmq:
    # 集群
    addresses: ${common.rabbitmq.addresses}
  redis:
    pool:
      max-active: ${common.redis.pool.maxActive:8}
      max-wait: ${common.redis.pool.maxWaitMillis:-1}
      max-idle: ${common.redis.pool.maxIdle:8}
      min-idle: ${common.redis.pool.minIdle:0}
    cluster:
      max-redirects: 6
      nodes: ${common.redis.addresses}
    database: ${common.redis.healthcheck.database:0}
    host: ${common.redis.healthcheck.host}
    port: ${common.redis.healthcheck.port}
    timeout: ${common.redis.healthcheck.timeout:5000}
#        nodes: 10.40.9.195:7000,10.40.9.195:7001,10.40.9.195:7002,10.40.9.195:7003,10.40.9.195:7004,10.40.9.195:7005
 #     password: ${common.redis.password}
  datasource:
    driver-class-name: ${common.operation.datasource.driverClassName}
#    url: ${common.operation.datasource.url}
    #url: jdbc:mysql://192.168.87.195:8806,192.168.87.195:8807/init_system?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false&roundRobinLoadBalance=true
#    username: ${common.operation.datasource.username}
#    password: ${common.operation.datasource.password}
    #url: jdbc:mysql://192.168.87.211:3306/system?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false&roundRobinLoadBalance=true
    #username: to4GSzhR6JU=
    #password: aL3+VIbS+o8=
    initialize: true
    continue-on-error: true
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,slf4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    logabandoned: true
    master:
      url: ${common.operation.datasource.master.url}
      username: ${common.operation.datasource.master.username}
      password: ${common.operation.datasource.master.password}
    business:
#      url: ${common.operation.datasource.business.url}
#      username: ${common.operation.datasource.business.username}
#      password: ${common.operation.datasource.business.password}
      url: ${common.operation.datasource.master.url}
      username: ${common.operation.datasource.master.username}
      password: ${common.operation.datasource.master.password}
  aop:
    auto: true
    proxy-target-class: true


server:
  port: ${module.operation.port}
  contextPath: /
feign:
    hystrix:
      enabled: true  # 默认false，hystrix必须enabled=TRUE
    httpclient:
      enabled: true
    client:
      config:
        ${provider.activity-module}:
          connectTimeout: 50000
          readTimeout: 50000
#hystrix 熔断机制
#hystrix:
#  shareSecurityContext: true
#  command:
#    default:
#      circuitBreaker:
#        sleepWindowInMilliseconds: 100000
#        forceClosed: true
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 600000
hystrix:
  shareSecurityContext: true
  metrics:
    enabled: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 10000
        forceClosed: true
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.sida.dcloud.*.po
  config-location: classpath:mapper/config/mybatis-configuration.xml

security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqBM+s8fK9psrzkdRjEAHSMGW+jRBn0hcSe9UPgiNEUTIUZtRp0Mf7sSxYOh5neKrGyWr9tuBAhwiM1HOlEUumVY8ddsl9YhF3ZUXfl9RfTF9ibY6WvXZo9Lpw+ZuQJ3fwH9TRl5sdSP3U6FyLmljaQBh++m4fahzNrHJJXvCZdrHV5AdkqQmZnBl/QpzAE1dD9C8dXsnhSYv9djoxXk+DvbNvdYaYYghf+EzJCZO5OkSYUZbW0KhWsqXfjMt8kYC1CsRh8shqRhZ4BpJFY8sXpGQdWuU9ZRnQaOQRrh5lmuMQ61ZR0YsKfO8lof27Opsj45S0vdXt0hzBBW4VXa05wIDAQAB
          -----END PUBLIC KEY-----
#        key-uri:
      id: openid
      service-id: ${PREFIX:}operation
  ignored: sysUserOperation/generateMobileVerifyCode,sysUserOperation/verifyBindStatus,sysUserOperation/bindMobile,sysUserOperation/bindNewMobile,/commonUser/findCommonUserById*,sysUserOperation/testDistributeTransaction


eureka:
  client:
    healthcheck:
      enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖）
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${module.operation.port}
    status-page-url: http://${spring.cloud.client.ipAddress}:${service.security.edge.port}/apis/operation/swagger-ui.html
    ip-address: ${spring.cloud.client.ipAddress}
    lease-expiration-duration-in-seconds: @lease-expiration-duration-in-seconds@
    lease-renewal-interval-in-seconds: @lease-renewal-interval-in-seconds@
    status-page-url-path: /info
    health-check-url-path: /health

tm:
  manager:
    url: @tm-manager-url@
logging:
  level:
    com:
      codingapi: warn
#Ribbon的负载均衡策略
#ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon.MaxAutoRetriesNextServer: 0

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 50000
  ConnectTimeout: 50000

management:
  health:
    redis:
      enabled: false
    mongo:
      enabled: false

info:
  app:
    name: operation-module
    auchor: Xiruo.Jiang
    version: 1.0
  build:
    artifactId: operation-module
    version: 1.0-SNAPSHOT
    date: 2018-9-18
